chore: Migrate to github
famedly/synapse-token-authenticator pull request #25
Opened 2023-10-09 06:50 UTC by emgrav

Closes #23

2023-10-09 07:35 UTC, nikzen submitted a review, later dismissed

2023-10-17 15:40 UTC, skomski submitted a review, later dismissed

2023-10-17 15:45 UTC, emgrav commented
Looks like you're the only available codeowner here @jcgruenhage, could you give it a look? :D

2023-10-17 17:05 UTC, jcgruenhage requested changes
Lgtm otherwise

2023-10-17 17:05 UTC, jcgruenhage commented on pyproject.toml
> +base-cov = "pytest --cov-report=lcov:../base.lcov --cov-config=pyproject.toml --cov=synapse_token_authenticator --cov=tests"
These should live in the ci env below, not in the default env

2023-10-18 13:48 UTC, jcgruenhage approved these changes

2023-10-18 14:03 UTC, merged