Add custom jwt flow
famedly/synapse-token-authenticator pull request #35
Opened 2024-04-23 17:00 UTC by sirewix

Closes https://github.com/famedly/product-management/issues/1910

2024-05-06 07:02 UTC, emgrav approved these changes
Have you had a chance to manually test the flow against synapse? If not, please just do that to double check before merging

2024-05-06 17:01 UTC, sirewix commented
@emgrav checked, seems to be working. Also added bearer access token (configurable via config) for the server that has to be notified on user registration (forgot about it)

2024-05-13 05:31 UTC, emgrav requested changes
Looks great! I think this is pretty much good to go, there's just some documentation I think should be added. 

Additionally, we have the details of the flow documented internally, would it make sense to add a brief and generic description of the new flow in the README as well?

2024-05-13 05:31 UTC, emgrav commented on synapse_token_authenticator/config.py
> +        if custom_flow := other.get("custom_flow"):
All the new config options should be documented in the README.

2024-05-13 12:54 UTC, emgrav approved these changes

2024-05-13 13:03 UTC, merged